### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by bruce-brookshire** [paul-at/quill-rails5#7]
Is there a way to use this gem without using turbolinks?

**Comment by paul-at** [comment]
@flyrboy96 this gem doesn't support turbolinks and they usually have to be disabled for all incoming links to the page with the editor, for example using `data: { turbolinks: false }` html option.

Unless you have a reason to use Quill editor, I'd consider this gem deprecated in favour of built-in rich text editor in Rails 6: https://guides.rubyonrails.org/action_text_overview.html

**Comment by bruce-brookshire** [comment]
@paul-at thank you for your insight! I’m new to Rails and learning on the go. Appreciate it
